name: Automatic AI Product Creator

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # للتشغيل اليدوي
  schedule:
    - cron: '0 0 * * *' # للتشغيل التلقائي اليومي

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        pip install openai requests
    - name: Run Bot
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }} # استدعاء المفتاح
      run: |
        python bots/product_bot.py
